In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
import time
from pathlib import Path
from typing import Dict, Tuple, Optional, Union, Any, List
import warnings
import scanpy as sc
warnings.filterwarnings('ignore')

# Import additional libraries for neural network training
from sklearn.model_selection import train_test_split, StratifiedKFold, GroupShuffleSplit
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, average_precision_score
from sklearn.metrics import precision_recall_curve, roc_curve, roc_auc_score, average_precision_score, recall_score
from sklearn.utils.class_weight import compute_class_weight

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (
    Dense, Dropout, BatchNormalization, Input, Add, Activation, 
    MultiHeadAttention, LayerNormalization, Reshape, Flatten,
    GlobalAveragePooling1D, Embedding
)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint, LearningRateScheduler
from tensorflow.keras.regularizers import l1_l2
from tensorflow.keras import backend as K
from sklearn.ensemble import RandomForestClassifier

In [2]:
import scanpy.external as sce
import scanpy as sc

In [3]:
Apexigen = sc.read_h5ad('./Apexigen_data/Apexigen_gene_TCR_annotated_for_integration_real_case.h5ad')
Apexigen

AnnData object with n_obs × n_vars = 16286 × 15827
    obs: 'batch', 'n_counts', 'n_genes', 'outcome', 'patient', 'response', 'sample', 'timepoint', 'log_counts', 'mt_frac', 'scvi_r1', 'cell_class', 'cell_type', 'cell_type_scvi', 'cell_class_scvi', 'TRB_cdr3', 'TRA_cdr3'
    obsm: 'X_umap'
    layers: 'counts'

In [4]:
Apexigen.obs.to_csv('./Apexigen_data/Apexigen_obs_metadata_for_integration_real_case.csv')

In [13]:

gex = pd.read_csv('./Apexigen_data_pca_harmony_batch_correction_by_sample_embeddings.csv', index_col=0)
gex.shape

(16286, 50)

# PE + AE TCR

In [14]:
atchley = pd.read_csv("../data/atchley.txt", sep="\t")
# atchley['avg'] = atchley[['f1','f2','f3','f4','f5']] .sum(axis=0)
atchley
index_aa_converter = pd.DataFrame({"aa":atchley['amino.acid'].values, "pos": list(range(20))})

index_aa_converter.index = index_aa_converter['aa'].values
index_aa_converter.pop("aa")
index_aa_converter
atchley.pop('amino.acid')
atchley

cols = atchley.columns
cols
for col in cols:
    atchley[col] =  pd.to_numeric(atchley[col].str.replace("−", "-"), errors='coerce')
atchley['avg'] = atchley.sum(axis=1)
atchley
atchley_aa = pd.concat([index_aa_converter.reset_index(), atchley], axis=1)
atchley_aa
atchley_amino_prop = pd.concat([pd.DataFrame([[0]*atchley_aa.shape[1]],columns=atchley_aa.columns),atchley_aa], axis=0)
atchley_amino_prop
atchley_aa = atchley_amino_prop
atchley_aa.iloc[0,0]='*'
atchley_aa
# word_vectors = np.array(atchley_amino_prop)
word_vectors = np.array(atchley_amino_prop.iloc[:,2:8])
word_vectors.shape

(21, 6)

In [15]:
# We use aa that has length of at most 50
def get_atchley(receptor_seq, length = 35):
    res_atchley = np.zeros((length), dtype='int')
    # print(len(receptor_seq))
    if (len(receptor_seq) <= length):
        for l in range(len(receptor_seq)):
            # print(receptor_seq[l])
            if receptor_seq[l] in index_aa_converter.index:
                res_atchley[l] = 1+index_aa_converter.loc[receptor_seq[l]].values[0]
            else:
                res_atchley[l] = np.random.randint(0,20)
            # res_atchley[l,:] =  atchley.loc[index_aa_converter.loc[receptor_seq[l]].values[0]].values #atchley.loc[receptor_seq[l]]
            # res_atchley = res_atchley.append(atchley.loc[s])
    else:
        for l in range(length):
            # print(receptor_seq[l])
            if receptor_seq[l] in index_aa_converter.index:
                # print(index_aa_converter.loc[receptor_seq[l]].values[0])
                res_atchley[l] = 1+index_aa_converter.loc[receptor_seq[l]].values[0]
            else:
                res_atchley[l] = np.random.randint(0,20)
            # res_atchley[l,:] =  atchley.loc[index_aa_converter.loc[receptor_seq[l]].values[0]].values #atchley.loc[receptor_seq[l]]
            # res_atchley = res_atchley.append(atchley.loc[s])
    return res_atchley

In [16]:
# The input of AAEmbedding is the vectorization of amino acid sequence, i.e., the order of each amino acid letter base in the 
# list of 20 amino acid, we can obtain the input by using get_atchley function
class AAEmbedding(tf.keras.layers.Layer):
    def __init__(self, word_vectors):
        super(AAEmbedding, self).__init__()
        self.word_vectors = tf.constant(word_vectors, dtype=tf.float32)

    def call(self, inputs):
        embedded_inputs = tf.nn.embedding_lookup(self.word_vectors, inputs)
        return embedded_inputs

In [17]:
def positional_encoding(depth, length=25):
  depth = depth
  # print(depth)
  positions = np.arange(length)[:, np.newaxis]   
  positions = np.repeat(positions, depth, axis=1)
  # print(np.repeat(positions, 6, axis=1))
  # print(positions)  # (seq, 1)
  # depths = np.arange(depth)[np.newaxis, :]/depth   # (1, depth)
  # print(depths.shape)
  angle_rates = 1 / (1000)         # (1, depth)
  angle_rads = positions * angle_rates      # (pos, depth)
  # print("Angle radian", angle_rads.shape)
  s = np.sin(angle_rads)[::2]
  c = 1- np.cos(angle_rads)[1::2]
  # print(s)
  # print(c)

  # pos_encoding = np.concatenate(
  #     [np.sin(angle_rads), np.cos(angle_rads)],
  #     axis=-1) 
  pos_encoding = np.vstack(
      [s, c]) 
  return tf.cast(pos_encoding, dtype=tf.float32)

In [18]:
class PositionalEmbedding(tf.keras.layers.Layer):
  def __init__(self, d_model, word_vectors,length = 25):
    super().__init__()
    self.d_model = d_model
    self.length = length
    # self.embedding = tf.keras.layers.Embedding(vocab_size, d_model, mask_zero=True) 
    self.embedding = AAEmbedding(word_vectors)
    self.pos_encoding = positional_encoding(depth=d_model, length=length)

  def compute_mask(self, *args, **kwargs):
    return self.embedding.compute_mask(*args, **kwargs)

  def call(self, x):
    # length = tf.shape(x)[1]

    # print("PositionalEmbedding input shape", x)
    x = self.embedding(x)
    # print(f"beginning x shape {x.shape}")
    # This factor sets the relative scale of the embedding and positonal_encoding.
    x *= tf.math.sqrt(tf.cast(self.d_model, tf.float32))
    # print('self position encoding value',self.pos_encoding[tf.newaxis, :50, :].shape)
    # print("x value before last line PositionEmbedding",x.shape)
    # scale = tf.cast(x != 0, tf.float32)
    # print(self.pos_encoding[tf.newaxis, :25, :])
    # print(scale.shape)
    # po = self.pos_encoding[tf.newaxis, :25, :]
    # scale = tf.reshape(scale,po.shape)
    # print(po.shape)
    # x = x + tf.multiply(self.pos_encoding[tf.newaxis, :25, :],scale)
    x = x + self.pos_encoding[tf.newaxis, :self.length, :]
    # print("Finish Positional Embedding")
    return x

In [19]:
d_model = 6
pt = PositionalEmbedding(d_model=d_model,word_vectors=word_vectors,length=35)

In [20]:
AA_embed = AAEmbedding(word_vectors)
AA_eem = AA_embed(get_atchley("CASSLGTDTQYF"))
# pt(get_atchley("CASSLGTDTQYF"))

# We do for random split

In [21]:
Apexigen.obs

,batch,n_counts,n_genes,outcome,patient,response,sample,timepoint,log_counts,mt_frac,scvi_r1,cell_class,cell_type,cell_type_scvi,cell_class_scvi,TRB_cdr3,TRA_cdr3
AAACCTGAGGCGCTCT-1-4,4,1756.0,627,PD,05,pathCR,05_post,post_CD40,7.470794,0.032460,3,CD4T_naive,CD4T_naive3,CD4T_naive2,CD4T_naive,CASSVATAGGIGYTF,CAMREGWNTGTASKLTF
AAACCTGCATGCCACG-1-4,4,1787.0,707,PD,05,pathCR,05_post,post_CD40,7.488294,0.029659,2,CD4T_naive,CD4T_naive1,CD4T_naive1,CD4T_naive,CASSLGGVNTGELFF,CAASTGNDMRF
AAACCTGTCTCCTATA-1-6,6,1825.0,864,HD,HD_01,HD,HD_03,nan,7.509336,0.055342,3,CD4T_naive,CD4T_naive2,CD4T_naive2,CD4T_naive,CASSQGGLGLGGAVQPQHF,CAAGSGATNKLIF
AAACGGGAGGGATACC-1-8,8,974.0,470,PD,01,nopathCR,01_LTF2,follow_up,6.881412,0.075975,0,CD8T,CD8T_GrH1,CD8_GrH,CD8_T,CASSRLAEVNEQFF,CAESRSGGSYIPTF
AAACGGGCATCGGAAG-1-3,3,2800.0,865,PD,04,pathCR,04_surgery,surgery,7.937375,0.024286,7,CD4T_naive,CD4T_naive3,CD4T_naive3,CD4T_naive,CASSAGGARVSYEQYF,CAVFSGSRLTF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTCCTCCACTCGACG-1_05_post,0,4706.0,1357,PD,05,pathCR,05_post,post_CD40,8.456594,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,CASSLDSYGYTF,CAVNMDRGSTLGRLYF
TTTGCGCGTGTGCCTG-1_05_post,0,2891.0,1380,PD,05,pathCR,05_post,post_CD40,7.969358,0.000000,3,CD8_Tcell,CD8T_GrK,CD8T_GrH,CD8_T,CASSLSYSEETQYF,CLVGERGSTLGRLYF
TTTGGTTCACCAGCAC-1_05_post,0,3474.0,1338,PD,05,pathCR,05_post,post_CD40,8.153062,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,CASTQNGGDTQYF,CAVTLGGSYIPTF
TTTGGTTGTTCTGGTA-1_05_post,0,4632.0,1231,PD,05,pathCR,05_post,post_CD40,8.440744,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,CASSNVRRSRDSPLHF,CAIRDGGAQKLVF
TTTGTCATCTGTTGAG-1_05_post,0,3331.0,1533,PD,05,pathCR,05_post,post_CD40,8.111028,0.000000,4,CD8_Tcell,CD8T_GrH,CD8T_GrB,CD8_T,CAWSVAGEGYTF,CAVPQTGANNLFF

In [22]:
train_TCR_df = Apexigen.obs
train_TCR_df

,batch,n_counts,n_genes,outcome,patient,response,sample,timepoint,log_counts,mt_frac,scvi_r1,cell_class,cell_type,cell_type_scvi,cell_class_scvi,TRB_cdr3,TRA_cdr3
AAACCTGAGGCGCTCT-1-4,4,1756.0,627,PD,05,pathCR,05_post,post_CD40,7.470794,0.032460,3,CD4T_naive,CD4T_naive3,CD4T_naive2,CD4T_naive,CASSVATAGGIGYTF,CAMREGWNTGTASKLTF
AAACCTGCATGCCACG-1-4,4,1787.0,707,PD,05,pathCR,05_post,post_CD40,7.488294,0.029659,2,CD4T_naive,CD4T_naive1,CD4T_naive1,CD4T_naive,CASSLGGVNTGELFF,CAASTGNDMRF
AAACCTGTCTCCTATA-1-6,6,1825.0,864,HD,HD_01,HD,HD_03,nan,7.509336,0.055342,3,CD4T_naive,CD4T_naive2,CD4T_naive2,CD4T_naive,CASSQGGLGLGGAVQPQHF,CAAGSGATNKLIF
AAACGGGAGGGATACC-1-8,8,974.0,470,PD,01,nopathCR,01_LTF2,follow_up,6.881412,0.075975,0,CD8T,CD8T_GrH1,CD8_GrH,CD8_T,CASSRLAEVNEQFF,CAESRSGGSYIPTF
AAACGGGCATCGGAAG-1-3,3,2800.0,865,PD,04,pathCR,04_surgery,surgery,7.937375,0.024286,7,CD4T_naive,CD4T_naive3,CD4T_naive3,CD4T_naive,CASSAGGARVSYEQYF,CAVFSGSRLTF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTCCTCCACTCGACG-1_05_post,0,4706.0,1357,PD,05,pathCR,05_post,post_CD40,8.456594,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,CASSLDSYGYTF,CAVNMDRGSTLGRLYF
TTTGCGCGTGTGCCTG-1_05_post,0,2891.0,1380,PD,05,pathCR,05_post,post_CD40,7.969358,0.000000,3,CD8_Tcell,CD8T_GrK,CD8T_GrH,CD8_T,CASSLSYSEETQYF,CLVGERGSTLGRLYF
TTTGGTTCACCAGCAC-1_05_post,0,3474.0,1338,PD,05,pathCR,05_post,post_CD40,8.153062,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,CASTQNGGDTQYF,CAVTLGGSYIPTF
TTTGGTTGTTCTGGTA-1_05_post,0,4632.0,1231,PD,05,pathCR,05_post,post_CD40,8.440744,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,CASSNVRRSRDSPLHF,CAIRDGGAQKLVF
TTTGTCATCTGTTGAG-1_05_post,0,3331.0,1533,PD,05,pathCR,05_post,post_CD40,8.111028,0.000000,4,CD8_Tcell,CD8T_GrH,CD8T_GrB,CD8_T,CAWSVAGEGYTF,CAVPQTGANNLFF

In [23]:
train_TCR = pd.DataFrame()
for s in train_TCR_df.TRB_cdr3.values:
    train_TCR = pd.concat([train_TCR, pd.DataFrame(pt(get_atchley(s)).numpy().reshape(1,35*d_model))], axis=0)

In [24]:
train_TCR.to_csv(f"train_TCR_PE_only_no_AE_Apexigen.csv", index=False)

In [25]:

latent_dim = 128
input_dim = train_TCR.shape[1]
# Encoder
inp = keras.Input(shape=(input_dim,), name='encoder_input')
x = keras.layers.Dense(164)(inp)
x = keras.layers.BatchNormalization()(x)
latent = keras.layers.Dense(latent_dim, name="latent", activation="relu")(x)

# Decoder
x = keras.layers.Dense(164)(latent)
x = keras.layers.BatchNormalization()(x)
out = keras.layers.Dense(input_dim, activation="linear", name='decoder_output')(x) # Linear activation for reconstruction

# Model
model_random_split = keras.Model(inputs=inp, outputs=out, name="tcr_autoencoder")
model_random_split.compile(optimizer=keras.optimizers.Adam(1e-3), loss="mse")

In [26]:
model_random_split.fit(train_TCR, train_TCR, epochs=200, batch_size=64, validation_data=(train_TCR, train_TCR))

Epoch 1/200

2026-01-18 22:17:19.659632: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz

255/255 [==============================] - 1s 2ms/step - loss: 3.9358 - val_loss: 0.6364
Epoch 2/200
255/255 [==============================] - 0s 1ms/step - loss: 0.5348 - val_loss: 0.2325
Epoch 3/200
255/255 [==============================] - 0s 1ms/step - loss: 0.3237 - val_loss: 0.1337
Epoch 4/200
255/255 [==============================] - 0s 1ms/step - loss: 0.2628 - val_loss: 0.0917
Epoch 5/200
255/255 [==============================] - 0s 1ms/step - loss: 0.2337 - val_loss: 0.0794
Epoch 6/200
255/255 [==============================] - 1s 2ms/step - loss: 0.2336 - val_loss: 0.0888
Epoch 7/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2217 - val_loss: 0.0556
Epoch 8/200
255/255 [==============================] - 1s 2ms/step - loss: 0.2178 - val_loss: 0.0553
Epoch 9/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2113 - val_loss: 0.0550
Epoch 10/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2055 - val_loss: 0.0540
Epoch 11/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2096 - val_loss: 0.0537
Epoch 12/200
255/255 [==============================] - 1s 2ms/step - loss: 0.2072 - val_loss: 0.0733
Epoch 13/200
255/255 [==============================] - 0s 2ms/step - loss: 0.2048 - val_loss: 0.0451
Epoch 14/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1927 - val_loss: 0.0536
Epoch 15/200
255/255 [==============================] - 0s 1ms/step - loss: 0.2003 - val_loss: 0.0658
Epoch 16/200
255/255 [==============================] - 0s 1ms/step - loss: 0.2027 - val_loss: 0.0337
Epoch 17/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1951 - val_loss: 0.0366
Epoch 18/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1986 - val_loss: 0.0691
Epoch 19/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1930 - val_loss: 0.0347
Epoch 20/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1922 - val_loss: 0.0414
Epoch 21/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1924 - val_loss: 0.0615
Epoch 22/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1898 - val_loss: 0.0614
Epoch 23/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1956 - val_loss: 0.0530
Epoch 24/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1933 - val_loss: 0.0325
Epoch 25/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1903 - val_loss: 0.0556
Epoch 26/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1910 - val_loss: 0.0320
Epoch 27/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1929 - val_loss: 0.0301
Epoch 28/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1939 - val_loss: 0.0578
Epoch 29/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1856 - val_loss: 0.0314
Epoch 30/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1924 - val_loss: 0.0343
Epoch 31/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1886 - val_loss: 0.0450
Epoch 32/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1874 - val_loss: 0.0357
Epoch 33/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1923 - val_loss: 0.0280
Epoch 34/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1879 - val_loss: 0.0452
Epoch 35/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1906 - val_loss: 0.0417
Epoch 36/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1816 - val_loss: 0.0317
Epoch 37/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1821 - val_loss: 0.0374
Epoch 38/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1846 - val_loss: 0.0424
Epoch 39/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1829 - val_loss: 0.0427
Epoch 40/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1864 - val_loss: 0.0520
Epoch 41/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1878 - val_loss: 0.0347
Epoch 42/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1934 - val_loss: 0.0342
Epoch 43/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1864 - val_loss: 0.0273
Epoch 44/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1868 - val_loss: 0.0247
Epoch 45/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1835 - val_loss: 0.0381
Epoch 46/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1878 - val_loss: 0.0428
Epoch 47/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1894 - val_loss: 0.0289
Epoch 48/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1895 - val_loss: 0.0268
Epoch 49/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1843 - val_loss: 0.0433
Epoch 50/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1854 - val_loss: 0.0270
Epoch 51/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1855 - val_loss: 0.0348
Epoch 52/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1841 - val_loss: 0.0304
Epoch 53/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1862 - val_loss: 0.0547
Epoch 54/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1866 - val_loss: 0.0432
Epoch 55/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1889 - val_loss: 0.0296
Epoch 56/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1873 - val_loss: 0.0365
Epoch 57/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1856 - val_loss: 0.0439
Epoch 58/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1826 - val_loss: 0.0236
Epoch 59/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1838 - val_loss: 0.0281
Epoch 60/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1813 - val_loss: 0.0287
Epoch 61/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1847 - val_loss: 0.0291
Epoch 62/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1783 - val_loss: 0.0228
Epoch 63/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1827 - val_loss: 0.0282
Epoch 64/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1838 - val_loss: 0.0212
Epoch 65/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1897 - val_loss: 0.0343
Epoch 66/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1822 - val_loss: 0.0358
Epoch 67/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1793 - val_loss: 0.0303
Epoch 68/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1838 - val_loss: 0.0310
Epoch 69/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1794 - val_loss: 0.0340
Epoch 70/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1827 - val_loss: 0.0491
Epoch 71/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1796 - val_loss: 0.0271
Epoch 72/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1866 - val_loss: 0.0414
Epoch 73/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1840 - val_loss: 0.0405
Epoch 74/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1862 - val_loss: 0.0240
Epoch 75/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1823 - val_loss: 0.0435
Epoch 76/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1752 - val_loss: 0.0303
Epoch 77/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1825 - val_loss: 0.0270
Epoch 78/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1780 - val_loss: 0.0335
Epoch 79/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1759 - val_loss: 0.0211
Epoch 80/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1817 - val_loss: 0.0251
Epoch 81/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1803 - val_loss: 0.0245
Epoch 82/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1747 - val_loss: 0.0396
Epoch 83/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1773 - val_loss: 0.0352
Epoch 84/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1780 - val_loss: 0.0473
Epoch 85/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1726 - val_loss: 0.0395
Epoch 86/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1685 - val_loss: 0.0349
Epoch 87/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1834 - val_loss: 0.0334
Epoch 88/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1816 - val_loss: 0.0533
Epoch 89/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1700 - val_loss: 0.0207
Epoch 90/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1733 - val_loss: 0.0252
Epoch 91/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1792 - val_loss: 0.0253
Epoch 92/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1751 - val_loss: 0.0279
Epoch 93/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1809 - val_loss: 0.0318
Epoch 94/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1745 - val_loss: 0.0245
Epoch 95/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1790 - val_loss: 0.0276
Epoch 96/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1729 - val_loss: 0.0354
Epoch 97/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1814 - val_loss: 0.0293
Epoch 98/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1792 - val_loss: 0.0391
Epoch 99/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1803 - val_loss: 0.0340
Epoch 100/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1785 - val_loss: 0.0224
Epoch 101/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1756 - val_loss: 0.0745
Epoch 102/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1779 - val_loss: 0.0274
Epoch 103/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1752 - val_loss: 0.0338
Epoch 104/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1877 - val_loss: 0.0243
Epoch 105/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1752 - val_loss: 0.0832
Epoch 106/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1786 - val_loss: 0.0470
Epoch 107/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1822 - val_loss: 0.0240
Epoch 108/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1762 - val_loss: 0.0339
Epoch 109/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1775 - val_loss: 0.0433
Epoch 110/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1742 - val_loss: 0.0228
Epoch 111/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1660 - val_loss: 0.0155
Epoch 112/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1759 - val_loss: 0.0355
Epoch 113/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1734 - val_loss: 0.0222
Epoch 114/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1742 - val_loss: 0.0290
Epoch 115/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1763 - val_loss: 0.0183
Epoch 116/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1732 - val_loss: 0.0216
Epoch 117/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1780 - val_loss: 0.0355
Epoch 118/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1723 - val_loss: 0.0392
Epoch 119/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1751 - val_loss: 0.0294
Epoch 120/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1793 - val_loss: 0.0332
Epoch 121/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1691 - val_loss: 0.0189
Epoch 122/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1721 - val_loss: 0.0462
Epoch 123/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1736 - val_loss: 0.0207
Epoch 124/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1787 - val_loss: 0.0276
Epoch 125/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1774 - val_loss: 0.0281
Epoch 126/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1712 - val_loss: 0.0212
Epoch 127/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1714 - val_loss: 0.0248
Epoch 128/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1792 - val_loss: 0.0379
Epoch 129/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1728 - val_loss: 0.0361
Epoch 130/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1769 - val_loss: 0.0191
Epoch 131/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1791 - val_loss: 0.0247
Epoch 132/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1745 - val_loss: 0.0197
Epoch 133/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1735 - val_loss: 0.0185
Epoch 134/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1766 - val_loss: 0.0497
Epoch 135/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1711 - val_loss: 0.0265
Epoch 136/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1738 - val_loss: 0.0335
Epoch 137/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1759 - val_loss: 0.0159
Epoch 138/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1733 - val_loss: 0.0325
Epoch 139/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1716 - val_loss: 0.0229
Epoch 140/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1733 - val_loss: 0.0174
Epoch 141/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1760 - val_loss: 0.0397
Epoch 142/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1750 - val_loss: 0.0234
Epoch 143/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1689 - val_loss: 0.0427
Epoch 144/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1735 - val_loss: 0.0235
Epoch 145/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1735 - val_loss: 0.0367
Epoch 146/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1689 - val_loss: 0.0244
Epoch 147/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1703 - val_loss: 0.0354
Epoch 148/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1702 - val_loss: 0.0198
Epoch 149/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1770 - val_loss: 0.0309
Epoch 150/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1783 - val_loss: 0.0758
Epoch 151/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1697 - val_loss: 0.0255
Epoch 152/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1743 - val_loss: 0.0354
Epoch 153/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1777 - val_loss: 0.0261
Epoch 154/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1688 - val_loss: 0.0260
Epoch 155/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1729 - val_loss: 0.0228
Epoch 156/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1699 - val_loss: 0.0295
Epoch 157/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1679 - val_loss: 0.0202
Epoch 158/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1676 - val_loss: 0.0510
Epoch 159/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1747 - val_loss: 0.0824
Epoch 160/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1728 - val_loss: 0.0281
Epoch 161/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1703 - val_loss: 0.0357
Epoch 162/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1766 - val_loss: 0.0244
Epoch 163/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1697 - val_loss: 0.0194
Epoch 164/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1680 - val_loss: 0.0139
Epoch 165/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1721 - val_loss: 0.0213
Epoch 166/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1685 - val_loss: 0.0203
Epoch 167/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1650 - val_loss: 0.0177
Epoch 168/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1702 - val_loss: 0.0285
Epoch 169/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1706 - val_loss: 0.0238
Epoch 170/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1648 - val_loss: 0.0451
Epoch 171/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1681 - val_loss: 0.0246
Epoch 172/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1715 - val_loss: 0.0411
Epoch 173/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1693 - val_loss: 0.0276
Epoch 174/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1728 - val_loss: 0.0174
Epoch 175/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1711 - val_loss: 0.0263
Epoch 176/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1683 - val_loss: 0.0251
Epoch 177/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1703 - val_loss: 0.0236
Epoch 178/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1753 - val_loss: 0.0272
Epoch 179/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1722 - val_loss: 0.0385
Epoch 180/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1799 - val_loss: 0.0354
Epoch 181/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1710 - val_loss: 0.0263
Epoch 182/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1669 - val_loss: 0.0365
Epoch 183/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1656 - val_loss: 0.0350
Epoch 184/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1669 - val_loss: 0.0199
Epoch 185/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1718 - val_loss: 0.0228
Epoch 186/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1736 - val_loss: 0.0429
Epoch 187/200
255/255 [==============================] - 1s 2ms/step - loss: 0.1671 - val_loss: 0.0208
Epoch 188/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1644 - val_loss: 0.0254
Epoch 189/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1666 - val_loss: 0.0198
Epoch 190/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1679 - val_loss: 0.0247
Epoch 191/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1754 - val_loss: 0.0251
Epoch 192/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1679 - val_loss: 0.0146
Epoch 193/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1707 - val_loss: 0.0492
Epoch 194/200
255/255 [==============================] - 0s 2ms/step - loss: 0.1677 - val_loss: 0.0188
Epoch 195/200
255/255 [==============================] - 0s 1ms/step - loss: 0.1723 - val_loss: 0.0207
Epoch 196/200

In [27]:
model_random_split.save_weights(f'./smart_aligned_v2_TCR_AE_PE_only_no_AE_Apexigen_weights.h5')

In [28]:
latent_model = keras.Model(model_random_split.input, model_random_split.get_layer("latent").output)
embeddings_TCR_PE = latent_model.predict(train_TCR, batch_size=64)

255/255 [==============================] - 0s 268us/step

In [29]:
np.save(f"train_TCR_with_PE_and_AE_embeddings_Apexigen.npy", embeddings_TCR_PE)

# Next,we would like to un ED for batch gene expression and AE of TCR (integration by ED)

# ED for raw gene random split

In [8]:
gex

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,1.087143,0.467443,2.992532,-0.600697,-3.994596,-3.333098,1.494854,-1.146100,1.571670,-3.118363,...,-0.210213,1.269835,0.131614,1.555858,-0.562283,0.154132,1.219355,-0.089831,-0.300811,0.098589
1,9.246613,-4.383909,-4.804466,-0.070527,1.494315,0.910335,2.323131,-1.229502,-1.463696,1.459822,...,0.890217,0.616105,-0.418397,0.040113,-0.075964,0.261941,1.278015,0.778815,-0.413370,0.533625
2,-4.378371,1.180819,-4.223704,-5.470704,0.444927,-0.000247,1.059516,0.668836,0.961870,1.295324,...,1.722274,0.045716,0.730128,1.226174,1.399147,-0.674245,0.482494,0.890334,-1.046426,-0.332977
3,-0.850734,5.800984,2.319241,0.621932,0.391961,1.471914,-1.820410,-1.887836,0.645741,-0.318717,...,-0.187072,0.493142,-0.507019,-0.700821,-0.482881,1.702497,-2.204038,0.750383,2.090266,-0.414377
4,7.510671,-3.492533,0.615445,-0.826791,-0.356948,-0.733857,-0.747724,-1.670011,-0.794903,-0.049055,...,0.420621,0.245370,-0.644681,-0.188387,-0.635079,0.767439,1.157366,0.416946,0.140676,-0.130281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145474,-0.928211,4.903222,-2.795438,-2.711269,-0.354280,-0.522040,-0.471457,-2.239837,-0.942964,0.537984,...,1.706733,-0.141238,1.290803,0.571046,2.032877,-0.091293,-2.120174,2.326794,-0.270818,2.348335
145475,-3.711599,5.466145,-1.662588,3.397898,-1.352260,2.653984,1.317506,2.093558,-0.908551,-1.140238,...,-0.622839,-0.013557,-0.371825,0.784568,-0.067285,-0.820746,-0.442909,-0.638775,-0.235357,-0.845757
145476,-0.427704,-4.652079,0.408053,-1.942324,-2.452670,2.487576,-1.482361,-0.260748,-0.498160,0.732487,...,0.760570,0.456670,-0.208458,-0.142902,-0.938427,0.216794,1.042893,-0.465932,-0.601186,0.570299
145477,7.317558,-4.430610,1.243477,0.069994,0.100587,-1.188651,-0.900679,-0.003285,-0.333207,-0.494998,...,1.442170,0.210964,0.092243,0.610511,-0.685681,-0.969873,-0.389187,0.062457,-0.254924,-0.485812
145478,-1.064071,-0.136134,-6.339934,-2.648893,0.004989,1.844719,-0.423443,0.104356,-0.364793,0.121357,...,-0.091932,-0.370638,-2.166635,1.360578,-0.636125,0.585416,-0.027639,-0.825234,-0.003541,-0.099900

In [9]:

embeddings_TCR_PE = np.load(f'train_TCR_with_PE_and_AE_embeddings_Apexigen.npy')

In [14]:
train_input_raw = gex

In [11]:
from tensorflow.keras import layers, Model

hidden_dim = 64
lr=1e-3
input_dim = train_input_raw.shape[1]
output_dim = embeddings_TCR_PE.shape[1]
inp = layers.Input(shape=(input_dim,), name="raw_gex_input")

# Encoder: Raw counts → latent space
x = layers.Dense(input_dim, activation="relu")(inp)
x = layers.BatchNormalization()(x)
x = layers.Dropout(0.2)(x)
x = layers.Dense(55, activation="tanh")(x)
x = layers.BatchNormalization()(x)
latent = layers.Dense(64, name="latent_layer")(x)

# Decoder: Latent → positional encoded TCR
d = layers.Dense(75, activation="relu")(latent)
d = layers.BatchNormalization()(d)
d = layers.Dropout(0.2)(d)
d = layers.Dense(96, activation="tanh")(d)
d = layers.BatchNormalization()(d)
out = layers.Dense(output_dim,name="pe_tcr_pred")(d)

model_ED_gex_batch_tcr = Model(inp, out, name="raw_gene2pe_tcr")
model_ED_gex_batch_tcr.compile(optimizer=tf.keras.optimizers.Adam(lr), loss="mae", metrics=["mae"])

In [15]:
model_ED_gex_batch_tcr.fit(
    train_input_raw, embeddings_TCR_PE,
    validation_data=(train_input_raw, embeddings_TCR_PE),
    epochs=500,
    batch_size=128
)
# model_ED_gex_tcr.save_weights('./output/experiments/neg_ratio_3_1/merged_embeddings/smart_aligned_v2_model_ED_gex_tcr_ED_gex_to_tcr_model_random_split_1_weights_train.h5')
model_ED_gex_batch_tcr.save_weights(f'./smart_aligned_v2_model_ED_batch_gex_tcr_ED_gex_to_tcr_model_Apexigen.weights.h5')
latent_model_gex_tcr_integration = tf.keras.Model(model_ED_gex_batch_tcr.input, model_ED_gex_batch_tcr.get_layer("latent_layer").output)
ED_integration_gex_tcr = latent_model_gex_tcr_integration.predict(train_input_raw, batch_size=64)
np.save(f"ED_integration_batch_gex_tcr_embeddings_train_Apexigen.npy", ED_integration_gex_tcr)

Epoch 1/500

2026-01-19 11:18:21.387694: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz

128/128 [==============================] - 1s 2ms/step - loss: 10.0800 - mae: 10.0800 - val_loss: 7.6361 - val_mae: 7.6361
Epoch 2/500
128/128 [==============================] - 0s 2ms/step - loss: 4.3112 - mae: 4.3112 - val_loss: 2.4140 - val_mae: 2.4140
Epoch 3/500
128/128 [==============================] - 0s 2ms/step - loss: 2.3258 - mae: 2.3258 - val_loss: 2.2827 - val_mae: 2.2827
Epoch 4/500
128/128 [==============================] - 0s 2ms/step - loss: 2.2838 - mae: 2.2838 - val_loss: 2.2608 - val_mae: 2.2608
Epoch 5/500
128/128 [==============================] - 0s 2ms/step - loss: 2.2681 - mae: 2.2681 - val_loss: 2.2463 - val_mae: 2.2463
Epoch 6/500
128/128 [==============================] - 0s 2ms/step - loss: 2.2507 - mae: 2.2507 - val_loss: 2.2307 - val_mae: 2.2307
Epoch 7/500
128/128 [==============================] - 0s 2ms/step - loss: 2.2345 - mae: 2.2345 - val_loss: 2.2143 - val_mae: 2.2143
Epoch 8/500
128/128 [==============================] - 0s 2ms/step - loss: 2.2182 - mae: 2.2182 - val_loss: 2.1961 - val_mae: 2.1961
Epoch 9/500
128/128 [==============================] - 0s 2ms/step - loss: 2.2041 - mae: 2.2041 - val_loss: 2.1813 - val_mae: 2.1813
Epoch 10/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1910 - mae: 2.1910 - val_loss: 2.1705 - val_mae: 2.1705
Epoch 11/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1780 - mae: 2.1780 - val_loss: 2.1547 - val_mae: 2.1547
Epoch 12/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1675 - mae: 2.1675 - val_loss: 2.1457 - val_mae: 2.1457
Epoch 13/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1556 - mae: 2.1556 - val_loss: 2.1375 - val_mae: 2.1375
Epoch 14/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1478 - mae: 2.1478 - val_loss: 2.1255 - val_mae: 2.1255
Epoch 15/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1375 - mae: 2.1375 - val_loss: 2.1208 - val_mae: 2.1208
Epoch 16/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1323 - mae: 2.1323 - val_loss: 2.1120 - val_mae: 2.1120
Epoch 17/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1276 - mae: 2.1276 - val_loss: 2.1091 - val_mae: 2.1091
Epoch 18/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1224 - mae: 2.1224 - val_loss: 2.1074 - val_mae: 2.1074
Epoch 19/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1206 - mae: 2.1206 - val_loss: 2.1033 - val_mae: 2.1033
Epoch 20/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1184 - mae: 2.1184 - val_loss: 2.1019 - val_mae: 2.1019
Epoch 21/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1183 - mae: 2.1183 - val_loss: 2.1021 - val_mae: 2.1021
Epoch 22/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1171 - mae: 2.1171 - val_loss: 2.1002 - val_mae: 2.1002
Epoch 23/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1143 - mae: 2.1143 - val_loss: 2.0984 - val_mae: 2.0984
Epoch 24/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1123 - mae: 2.1123 - val_loss: 2.1001 - val_mae: 2.1001
Epoch 25/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1115 - mae: 2.1115 - val_loss: 2.0993 - val_mae: 2.0993
Epoch 26/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1116 - mae: 2.1116 - val_loss: 2.0974 - val_mae: 2.0974
Epoch 27/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1108 - mae: 2.1108 - val_loss: 2.0973 - val_mae: 2.0973
Epoch 28/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1097 - mae: 2.1097 - val_loss: 2.0980 - val_mae: 2.0980
Epoch 29/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1114 - mae: 2.1114 - val_loss: 2.0970 - val_mae: 2.0970
Epoch 30/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1119 - mae: 2.1119 - val_loss: 2.0969 - val_mae: 2.0969
Epoch 31/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1097 - mae: 2.1097 - val_loss: 2.0962 - val_mae: 2.0962
Epoch 32/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1081 - mae: 2.1081 - val_loss: 2.0953 - val_mae: 2.0953
Epoch 33/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1083 - mae: 2.1083 - val_loss: 2.0938 - val_mae: 2.0938
Epoch 34/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1077 - mae: 2.1077 - val_loss: 2.0949 - val_mae: 2.0949
Epoch 35/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1060 - mae: 2.1060 - val_loss: 2.0932 - val_mae: 2.0932
Epoch 36/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1057 - mae: 2.1057 - val_loss: 2.0927 - val_mae: 2.0927
Epoch 37/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1054 - mae: 2.1054 - val_loss: 2.0938 - val_mae: 2.0938
Epoch 38/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1064 - mae: 2.1064 - val_loss: 2.0931 - val_mae: 2.0931
Epoch 39/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1052 - mae: 2.1052 - val_loss: 2.0910 - val_mae: 2.0910
Epoch 40/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1029 - mae: 2.1029 - val_loss: 2.0919 - val_mae: 2.0919
Epoch 41/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1051 - mae: 2.1051 - val_loss: 2.0905 - val_mae: 2.0905
Epoch 42/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1042 - mae: 2.1042 - val_loss: 2.0896 - val_mae: 2.0896
Epoch 43/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1037 - mae: 2.1037 - val_loss: 2.0893 - val_mae: 2.0893
Epoch 44/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1027 - mae: 2.1027 - val_loss: 2.0899 - val_mae: 2.0899
Epoch 45/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1032 - mae: 2.1032 - val_loss: 2.0894 - val_mae: 2.0894
Epoch 46/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1019 - mae: 2.1019 - val_loss: 2.0881 - val_mae: 2.0881
Epoch 47/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1018 - mae: 2.1018 - val_loss: 2.0885 - val_mae: 2.0885
Epoch 48/500
128/128 [==============================] - 0s 2ms/step - loss: 2.1012 - mae: 2.1012 - val_loss: 2.0858 - val_mae: 2.0858
Epoch 49/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1026 - mae: 2.1026 - val_loss: 2.0867 - val_mae: 2.0867
Epoch 50/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1017 - mae: 2.1017 - val_loss: 2.0870 - val_mae: 2.0870
Epoch 51/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1004 - mae: 2.1004 - val_loss: 2.0879 - val_mae: 2.0879
Epoch 52/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1025 - mae: 2.1025 - val_loss: 2.0869 - val_mae: 2.0869
Epoch 53/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1004 - mae: 2.1004 - val_loss: 2.0865 - val_mae: 2.0865
Epoch 54/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0998 - mae: 2.0998 - val_loss: 2.0870 - val_mae: 2.0870
Epoch 55/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0989 - mae: 2.0989 - val_loss: 2.0863 - val_mae: 2.0863
Epoch 56/500
128/128 [==============================] - 0s 1ms/step - loss: 2.1002 - mae: 2.1002 - val_loss: 2.0830 - val_mae: 2.0830
Epoch 57/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0972 - mae: 2.0972 - val_loss: 2.0837 - val_mae: 2.0837
Epoch 58/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0975 - mae: 2.0975 - val_loss: 2.0825 - val_mae: 2.0825
Epoch 59/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0989 - mae: 2.0989 - val_loss: 2.0858 - val_mae: 2.0858
Epoch 60/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0978 - mae: 2.0978 - val_loss: 2.0813 - val_mae: 2.0813
Epoch 61/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0960 - mae: 2.0960 - val_loss: 2.0807 - val_mae: 2.0807
Epoch 62/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0970 - mae: 2.0970 - val_loss: 2.0861 - val_mae: 2.0861
Epoch 63/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0971 - mae: 2.0971 - val_loss: 2.0795 - val_mae: 2.0795
Epoch 64/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0990 - mae: 2.0990 - val_loss: 2.0799 - val_mae: 2.0799
Epoch 65/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0947 - mae: 2.0947 - val_loss: 2.0804 - val_mae: 2.0804
Epoch 66/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0945 - mae: 2.0945 - val_loss: 2.0785 - val_mae: 2.0785
Epoch 67/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0951 - mae: 2.0951 - val_loss: 2.0811 - val_mae: 2.0811
Epoch 68/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0949 - mae: 2.0949 - val_loss: 2.0781 - val_mae: 2.0781
Epoch 69/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0947 - mae: 2.0947 - val_loss: 2.0781 - val_mae: 2.0781
Epoch 70/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0940 - mae: 2.0940 - val_loss: 2.0789 - val_mae: 2.0789
Epoch 71/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0936 - mae: 2.0936 - val_loss: 2.0782 - val_mae: 2.0782
Epoch 72/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0925 - mae: 2.0925 - val_loss: 2.0752 - val_mae: 2.0752
Epoch 73/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0935 - mae: 2.0935 - val_loss: 2.0766 - val_mae: 2.0766
Epoch 74/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0921 - mae: 2.0921 - val_loss: 2.0764 - val_mae: 2.0764
Epoch 75/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0927 - mae: 2.0927 - val_loss: 2.0758 - val_mae: 2.0758
Epoch 76/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0915 - mae: 2.0915 - val_loss: 2.0740 - val_mae: 2.0740
Epoch 77/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0922 - mae: 2.0922 - val_loss: 2.0745 - val_mae: 2.0745
Epoch 78/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0913 - mae: 2.0913 - val_loss: 2.0742 - val_mae: 2.0742
Epoch 79/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0885 - mae: 2.0885 - val_loss: 2.0741 - val_mae: 2.0741
Epoch 80/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0898 - mae: 2.0898 - val_loss: 2.0730 - val_mae: 2.0730
Epoch 81/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0916 - mae: 2.0916 - val_loss: 2.0717 - val_mae: 2.0717
Epoch 82/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0906 - mae: 2.0906 - val_loss: 2.0748 - val_mae: 2.0748
Epoch 83/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0906 - mae: 2.0906 - val_loss: 2.0725 - val_mae: 2.0725
Epoch 84/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0908 - mae: 2.0908 - val_loss: 2.0726 - val_mae: 2.0726
Epoch 85/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0901 - mae: 2.0901 - val_loss: 2.0721 - val_mae: 2.0721
Epoch 86/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0878 - mae: 2.0878 - val_loss: 2.0714 - val_mae: 2.0714
Epoch 87/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0905 - mae: 2.0905 - val_loss: 2.0730 - val_mae: 2.0730
Epoch 88/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0872 - mae: 2.0872 - val_loss: 2.0713 - val_mae: 2.0713
Epoch 89/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0885 - mae: 2.0885 - val_loss: 2.0741 - val_mae: 2.0741
Epoch 90/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0880 - mae: 2.0880 - val_loss: 2.0699 - val_mae: 2.0699
Epoch 91/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0886 - mae: 2.0886 - val_loss: 2.0737 - val_mae: 2.0737
Epoch 92/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0888 - mae: 2.0888 - val_loss: 2.0687 - val_mae: 2.0687
Epoch 93/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0876 - mae: 2.0876 - val_loss: 2.0704 - val_mae: 2.0704
Epoch 94/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0871 - mae: 2.0871 - val_loss: 2.0685 - val_mae: 2.0685
Epoch 95/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0873 - mae: 2.0873 - val_loss: 2.0692 - val_mae: 2.0692
Epoch 96/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0874 - mae: 2.0874 - val_loss: 2.0670 - val_mae: 2.0670
Epoch 97/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0869 - mae: 2.0869 - val_loss: 2.0690 - val_mae: 2.0690
Epoch 98/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0854 - mae: 2.0854 - val_loss: 2.0682 - val_mae: 2.0682
Epoch 99/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0849 - mae: 2.0849 - val_loss: 2.0669 - val_mae: 2.0669
Epoch 100/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0839 - mae: 2.0839 - val_loss: 2.0667 - val_mae: 2.0667
Epoch 101/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0842 - mae: 2.0842 - val_loss: 2.0650 - val_mae: 2.0650
Epoch 102/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0863 - mae: 2.0863 - val_loss: 2.0651 - val_mae: 2.0651
Epoch 103/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0842 - mae: 2.0842 - val_loss: 2.0713 - val_mae: 2.0713
Epoch 104/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0856 - mae: 2.0856 - val_loss: 2.0646 - val_mae: 2.0646
Epoch 105/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0845 - mae: 2.0845 - val_loss: 2.0639 - val_mae: 2.0639
Epoch 106/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0835 - mae: 2.0835 - val_loss: 2.0626 - val_mae: 2.0626
Epoch 107/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0845 - mae: 2.0845 - val_loss: 2.0659 - val_mae: 2.0659
Epoch 108/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0834 - mae: 2.0834 - val_loss: 2.0667 - val_mae: 2.0667
Epoch 109/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0845 - mae: 2.0845 - val_loss: 2.0642 - val_mae: 2.0642
Epoch 110/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0834 - mae: 2.0834 - val_loss: 2.0630 - val_mae: 2.0630
Epoch 111/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0841 - mae: 2.0841 - val_loss: 2.0629 - val_mae: 2.0629
Epoch 112/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0830 - mae: 2.0830 - val_loss: 2.0638 - val_mae: 2.0638
Epoch 113/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0823 - mae: 2.0823 - val_loss: 2.0647 - val_mae: 2.0647
Epoch 114/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0823 - mae: 2.0823 - val_loss: 2.0629 - val_mae: 2.0629
Epoch 115/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0816 - mae: 2.0816 - val_loss: 2.0614 - val_mae: 2.0614
Epoch 116/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0838 - mae: 2.0838 - val_loss: 2.0620 - val_mae: 2.0620
Epoch 117/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0815 - mae: 2.0815 - val_loss: 2.0627 - val_mae: 2.0627
Epoch 118/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0812 - mae: 2.0812 - val_loss: 2.0622 - val_mae: 2.0622
Epoch 119/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0837 - mae: 2.0837 - val_loss: 2.0612 - val_mae: 2.0612
Epoch 120/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0828 - mae: 2.0828 - val_loss: 2.0613 - val_mae: 2.0613
Epoch 121/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0829 - mae: 2.0829 - val_loss: 2.0599 - val_mae: 2.0599
Epoch 122/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0825 - mae: 2.0825 - val_loss: 2.0619 - val_mae: 2.0619
Epoch 123/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0795 - mae: 2.0795 - val_loss: 2.0628 - val_mae: 2.0628
Epoch 124/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0800 - mae: 2.0800 - val_loss: 2.0596 - val_mae: 2.0596
Epoch 125/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0790 - mae: 2.0790 - val_loss: 2.0572 - val_mae: 2.0572
Epoch 126/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0795 - mae: 2.0795 - val_loss: 2.0594 - val_mae: 2.0594
Epoch 127/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0792 - mae: 2.0792 - val_loss: 2.0623 - val_mae: 2.0623
Epoch 128/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0803 - mae: 2.0803 - val_loss: 2.0603 - val_mae: 2.0603
Epoch 129/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0810 - mae: 2.0810 - val_loss: 2.0577 - val_mae: 2.0577
Epoch 130/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0778 - mae: 2.0778 - val_loss: 2.0589 - val_mae: 2.0589
Epoch 131/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0795 - mae: 2.0795 - val_loss: 2.0577 - val_mae: 2.0577
Epoch 132/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0770 - mae: 2.0770 - val_loss: 2.0565 - val_mae: 2.0565
Epoch 133/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0759 - mae: 2.0759 - val_loss: 2.0561 - val_mae: 2.0561
Epoch 134/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0769 - mae: 2.0769 - val_loss: 2.0565 - val_mae: 2.0565
Epoch 135/500
128/128 [==============================] - 0s 1ms/step - loss: 2.0793 - mae: 2.0793 - val_loss: 2.0590 - val_mae: 2.0590
Epoch 136/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0800 - mae: 2.0800 - val_loss: 2.0576 - val_mae: 2.0576
Epoch 137/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0758 - mae: 2.0758 - val_loss: 2.0564 - val_mae: 2.0564
Epoch 138/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0790 - mae: 2.0790 - val_loss: 2.0559 - val_mae: 2.0559
Epoch 139/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0758 - mae: 2.0758 - val_loss: 2.0561 - val_mae: 2.0561
Epoch 140/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0761 - mae: 2.0761 - val_loss: 2.0547 - val_mae: 2.0547
Epoch 141/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0762 - mae: 2.0762 - val_loss: 2.0552 - val_mae: 2.0552
Epoch 142/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0765 - mae: 2.0765 - val_loss: 2.0544 - val_mae: 2.0544
Epoch 143/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0777 - mae: 2.0777 - val_loss: 2.0551 - val_mae: 2.0551
Epoch 144/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0778 - mae: 2.0778 - val_loss: 2.0547 - val_mae: 2.0547
Epoch 145/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0764 - mae: 2.0764 - val_loss: 2.0536 - val_mae: 2.0536
Epoch 146/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0798 - mae: 2.0798 - val_loss: 2.0539 - val_mae: 2.0539
Epoch 147/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0781 - mae: 2.0781 - val_loss: 2.0573 - val_mae: 2.0573
Epoch 148/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0771 - mae: 2.0771 - val_loss: 2.0551 - val_mae: 2.0551
Epoch 149/500
128/128 [==============================] - 0s 2ms/step - loss: 2.0772 - mae: 2.0772 - val_loss: 2.0560 - val_mae: 2.0560