In [1]:
import pandas as pd
import numpy as np

In [2]:
mc_pas = pd.read_csv('./McPAS-TCR.csv')
mc_pas

/var/folders/xy/jbfzznj17w73w_rdfj3xs11h0000gn/T/ipykernel_11961/748820045.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  mc_pas = pd.read_csv('./McPAS-TCR.csv')

,CDR3.alpha.aa,CDR3.beta.aa,Species,Category,Pathology,Pathology.Mesh.ID,Additional.study.details,Antigen.identification.method,Single.cell,NGS,...,TRAV,TRAJ,TRBV,TRBD,TRBJ,Reconstructed.J.annotation,CDR3.beta.nt,Mouse.strain,PubMed.ID,Remarks
0,NaN,ATSIRFTDTQYF,Human,Autoimmune,Celiac disease,D002503,6 days post oral gluten\nchallenge,1.0,Yes,Yes,...,TRAV8-6,NaN,TRBV7-2,NaN,TRBJ2-3,NaN,NaN,NaN,23878218,NaN
1,NaN,CAAAAASGAYEQYF,Human,Pathogens,M.Tuberculosis,D009169,Bulk,2.2,No,Yes,...,NaN,NaN,TRBV10-3,NaN,NaN,NaN,NaN,NaN,32341563,NaN
2,NaN,CAAADEEIGNQPQHF,Human,Pathogens,Hepatitis C virus,D016174,NaN,1.0,No,No,...,NaN,NaN,TRBV10-03,NaN,NaN,No,NaN,NaN,21160049,NaN
3,CAVRDSNYQLIW,CAAAGGPDTGELFF,Human,Pathogens,M. tuberculosis,D009169,NaN,2.2,Yes,Yes,...,NaN,TRAJ33,TRBV6-1,NaN,TRBJ2-2,NaN,NaN,NaN,30992377,NaN
4,NaN,CAAEDDTGGFKTIF,Human,Pathogens,Influenza,D009980,NaN,1.0,Yes,Yes,...,TRAV8-4:03,TRAJ45:01,TRBV25:01,NaN,TRBJ9:01,No,NaN,NaN,28300170,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40726,NaN,CASSPKRTRQLSIS,Human,Autoimmune,ARDS,D012128,Acute Respiratory Distress Syndrome,NaN,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37238695,TRBJ not suplied
40727,NaN,CASSPTRPAARRLS,Human,Autoimmune,ARDS,D012128,Acute Respiratory Distress Syndrome,NaN,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37238695,TRBJ not suplied
40728,NaN,CASSTRQLFTSVPP,Human,Autoimmune,ARDS,D012128,Acute Respiratory Distress Syndrome,NaN,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37238695,TRBJ not suplied
40729,NaN,CASSTPPAARRLGP,Human,Autoimmune,ARDS,D012128,Acute Respiratory Distress Syndrome,NaN,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37238695,TRBJ not suplied
40730,NaN,CASSAHRAGGLGRV,Human,Autoimmune,ARDS,D012128,Acute Respiratory Distress Syndrome,NaN,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37238695,TRBJ not suplied

In [3]:
mc_pas_human = mc_pas[mc_pas['Species'] == "Human"]
mc_pas_human

,CDR3.alpha.aa,CDR3.beta.aa,Species,Category,Pathology,Pathology.Mesh.ID,Additional.study.details,Antigen.identification.method,Single.cell,NGS,...,TRAV,TRAJ,TRBV,TRBD,TRBJ,Reconstructed.J.annotation,CDR3.beta.nt,Mouse.strain,PubMed.ID,Remarks
0,NaN,ATSIRFTDTQYF,Human,Autoimmune,Celiac disease,D002503,6 days post oral gluten\nchallenge,1.0,Yes,Yes,...,TRAV8-6,NaN,TRBV7-2,NaN,TRBJ2-3,NaN,NaN,NaN,23878218,NaN
1,NaN,CAAAAASGAYEQYF,Human,Pathogens,M.Tuberculosis,D009169,Bulk,2.2,No,Yes,...,NaN,NaN,TRBV10-3,NaN,NaN,NaN,NaN,NaN,32341563,NaN
2,NaN,CAAADEEIGNQPQHF,Human,Pathogens,Hepatitis C virus,D016174,NaN,1.0,No,No,...,NaN,NaN,TRBV10-03,NaN,NaN,No,NaN,NaN,21160049,NaN
3,CAVRDSNYQLIW,CAAAGGPDTGELFF,Human,Pathogens,M. tuberculosis,D009169,NaN,2.2,Yes,Yes,...,NaN,TRAJ33,TRBV6-1,NaN,TRBJ2-2,NaN,NaN,NaN,30992377,NaN
4,NaN,CAAEDDTGGFKTIF,Human,Pathogens,Influenza,D009980,NaN,1.0,Yes,Yes,...,TRAV8-4:03,TRAJ45:01,TRBV25:01,NaN,TRBJ9:01,No,NaN,NaN,28300170,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40726,NaN,CASSPKRTRQLSIS,Human,Autoimmune,ARDS,D012128,Acute Respiratory Distress Syndrome,NaN,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37238695,TRBJ not suplied
40727,NaN,CASSPTRPAARRLS,Human,Autoimmune,ARDS,D012128,Acute Respiratory Distress Syndrome,NaN,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37238695,TRBJ not suplied
40728,NaN,CASSTRQLFTSVPP,Human,Autoimmune,ARDS,D012128,Acute Respiratory Distress Syndrome,NaN,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37238695,TRBJ not suplied
40729,NaN,CASSTPPAARRLGP,Human,Autoimmune,ARDS,D012128,Acute Respiratory Distress Syndrome,NaN,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37238695,TRBJ not suplied
40730,NaN,CASSAHRAGGLGRV,Human,Autoimmune,ARDS,D012128,Acute Respiratory Distress Syndrome,NaN,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37238695,TRBJ not suplied

In [4]:
mc_pas_human['Pathology'].value_counts()

Pathology
M.Tuberculosis               16659
Influenza                     4211
Cytomegalovirus (CMV)         2745
M. tuberculosis               2116
Neoantigen                    1569
                             ...
Hepatocellular carcinoma         2
HTLV-1 (Chronic                  1
Diabetes type 2                  1
Carcinoma of uterine tube        1
Ovarian cancer                   1
Name: count, Length: 64, dtype: int64

In [5]:
mc_pas_human.columns

Index(['CDR3.alpha.aa', 'CDR3.beta.aa', 'Species', 'Category', 'Pathology',
       'Pathology.Mesh.ID', 'Additional.study.details',
       'Antigen.identification.method', 'Single.cell', 'NGS',
       'Antigen.protein', 'Protein.ID', 'Epitope.peptide', 'Epitope.ID', 'MHC',
       'Tissue', 'T.Cell.Type', 'T.cell.characteristics', 'CDR3.alpha.nt',
       'TRAV', 'TRAJ', 'TRBV', 'TRBD', 'TRBJ', 'Reconstructed.J.annotation',
       'CDR3.beta.nt', 'Mouse.strain', 'PubMed.ID', 'Remarks'],
      dtype='object')

In [6]:
mc_pas_human[['Epitope.peptide','Protein.ID','Epitope.ID']]

      Epitope.peptide Protein.ID Epitope.ID
0         PQPELPYPQPQ        NaN        NaN
1                 NaN        NaN        NaN
2           ATDALMTGY     P27958       4917
3                 NaN        NaN        NaN
4           GILGFVFTL     P03485      20354
...               ...        ...        ...
40726             NaN        NaN        NaN
40727             NaN        NaN        NaN
40728             NaN        NaN        NaN
40729             NaN        NaN        NaN
40730             NaN        NaN        NaN

[36474 rows x 3 columns]

In [7]:
mc_pas_human_peptide = mc_pas_human[['CDR3.beta.aa', 'Pathology','Epitope.peptide']]
mc_pas_human_peptide = mc_pas_human_peptide[~mc_pas_human_peptide['Epitope.peptide'].isnull()]
mc_pas_human_peptide = mc_pas_human_peptide[~(mc_pas_human_peptide['CDR3.beta.aa'].str.contains('\*') ==True)]
mc_pas_human_peptide.columns = ['CDR3','Epitope_type','Epitope']
mc_pas_human_peptide

,CDR3,Epitope_type,Epitope
0,ATSIRFTDTQYF,Celiac disease,PQPELPYPQPQ
2,CAAADEEIGNQPQHF,Hepatitis C virus,ATDALMTGY
4,CAAEDDTGGFKTIF,Influenza,GILGFVFTL
5,CAAFQGAQKLVF,HTLV-1,LLFGYPVYV
9,CAAGGQFYGYTF,Human immunodeficiency virus (HIV),KAFSPEVIPMF
...,...,...,...
39931,WQLRAYSRKTYGYTF,Merkel cell carcinoma,WEDLFCDESLSSPEPPSSSE
39933,YASSDKSLRSVDYGYTF,Merkel cell carcinoma,WEDLFCDESLSSPEPPSSSE
39934,YASSKNNFDGKTYG,Merkel cell carcinoma,WEDLFCDESLSSPEPPSSSE
39935,YASSKYARRQSRANVLTF,Merkel cell carcinoma,WEDLFCDESLSSPEPPSSSE
39936,YSSEDGRLLVDNEKLFF,Merkel cell carcinoma,WEDLFCDESLSSPEPPSSSE

In [8]:
vdjdb = pd.read_csv('./VDJ_db_human_033026.tsv', sep='\t')
vdjdb = vdjdb[vdjdb['Epitope species'] == "HomoSapiens"]
vdjdb = vdjdb[vdjdb['Gene'] == 'TRB']

In [9]:
vdjdb.columns

Index(['complex.id', 'Gene', 'CDR3', 'V', 'J', 'Species', 'MHC A', 'MHC B',
       'MHC class', 'Epitope', 'Epitope gene', 'Epitope species', 'Reference',
       'Method', 'Meta', 'CDR3fix', 'Score'],
      dtype='object')

In [10]:
vdjdb_clean = vdjdb[['CDR3','Epitope', 'Epitope gene']].copy()
vdjdb_clean.columns = ['CDR3','Epitope','Epitope_type']
vdjdb_clean

                   CDR3      Epitope Epitope_type
0          CASSLERDGYTF    VELGGGPGA          INS
1      CASSLEASSYNSPLHF    VELGGGPGA          INS
2          CASSLERETQYF    VELGGGPGA          INS
3        CASSPTTGGDEAFF  QVELGGGPGAG          INS
4       CASSLGPGQRETQYF    QVELGGGPG          INS
...                 ...          ...          ...
40081        CSAGTGELFF   ALDPHSGHFV         CDK4
40082     CSARVGDTGELFF    ALSPVIPHI         MLL2
40083    CASSYDSTTGELFF    ALSPVIPHI         MLL2
40084      CASTPGGYEQYF   KLFEFLVYGV      SMARCD3
40085       CASSQGYEQYF   KLFEFLVYGV      SMARCD3

[40086 rows x 3 columns]

In [11]:
IEDB_tumor_epitope = pd.read_csv('./Apexigen_data/IEDB_tumor_epitope.csv', index_col=0)
IEDB_tumor_epitope.rename(columns={"Epitope_Name":"peptide"}, inplace=True)
IEDB_tumor_epitope = IEDB_tumor_epitope.drop_duplicates(subset=['peptide'])
IEDB_tumor_epitope

             peptide
1          SLLMWITQC
2          AAGIGILTV
3         ELAGIGILTV
4          YLEPGPVTV
5          YLEPGAVTA
..               ...
373        VQTFLGISF
374    DPPALASTNAEVT
375       MPYGYVLNEF
376  GYNSYSVSNSEKHIM
377        TYDTVHRHL

[377 rows x 1 columns]

In [12]:
IEDB = pd.read_csv("./Apexigen_data/IEDB_clean_from_IEDB_matching_RMD_file.csv", index_col=0)
IEDB

,Receptor_Group IRI,Receptor_IEDB Receptor ID,Receptor_Reference Name,Receptor_Type,Reference_IEDB IRI,Epitope_IEDB IRI,Epitope_Name,Epitope_Source Molecule,Epitope_Source Organism,Assay_Type,...,Chain 2_CDR1 Start Curated,Chain 2_CDR1 End Curated,Chain 2_CDR1 Start Calculated,Chain 2_CDR1 End Calculated,Chain 2_CDR2 Curated,Chain 2_CDR2 Calculated,Chain 2_CDR2 Start Curated,Chain 2_CDR2 End Curated,Chain 2_CDR2 Start Calculated,Chain 2_CDR2 End Calculated
1,http://www.iedb.org/receptor/117,151,1G4,alphabeta,http://www.iedb.org/reference/1012513,http://www.iedb.org/epitope/59278,SLLMWITQC,Cancer/testis antigen 1,Homo sapiens (human),T cell,...,NaN,NaN,25.0,29.0,SVGAGI,SVGAGI,NaN,NaN,47.0,52.0
2,http://www.iedb.org/receptor/619,803,DMF4,alphabeta,http://www.iedb.org/reference/1012513,http://www.iedb.org/epitope/155,AAGIGILTV,Melanoma antigen recognized by T-cells 1,Homo sapiens (human),T cell,...,NaN,NaN,27.0,31.0,SYGVKD,SYGVKD,NaN,NaN,49.0,54.0
3,http://www.iedb.org/receptor/619,803,DMF4,alphabeta,http://www.iedb.org/reference/1023541,http://www.iedb.org/epitope/155,AAGIGILTV,Melanoma antigen recognized by T-cells 1,Homo sapiens (human),T cell,...,NaN,NaN,27.0,31.0,SYGVKD,SYGVKD,NaN,NaN,49.0,54.0
4,http://www.iedb.org/receptor/619,803,DMF4,alphabeta,http://www.iedb.org/reference/1023541,http://www.iedb.org/epitope/12941,ELAGIGILTV,melanoma-specific artificial polyepitopic immu...,Vaccinia virus (vaccinia virus VV),T cell,...,NaN,NaN,27.0,31.0,SYGVKD,SYGVKD,NaN,NaN,49.0,54.0
5,http://www.iedb.org/receptor/802,1023,PMEL17,alphabeta,http://www.iedb.org/reference/1029982,http://www.iedb.org/epitope/74641,YLEPGPVTV,NaN,NaN,T cell,...,NaN,NaN,27.0,31.0,FQGTGA,FQGTGA,NaN,NaN,49.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3152,http://www.iedb.org/receptor/202720,223146,w1051,alphabeta,http://www.iedb.org/reference/1031237,http://www.iedb.org/epitope/923446,KLLEIAPNC,large T antigen [Merkel cell polyomavirus],Merkel cell polyomavirus (MCPyV isolate R17b),T cell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3153,http://www.iedb.org/receptor/202721,223147,w878,alphabeta,http://www.iedb.org/reference/1031237,http://www.iedb.org/epitope/923446,KLLEIAPNC,large T antigen [Merkel cell polyomavirus],Merkel cell polyomavirus (MCPyV isolate R17b),T cell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3154,http://www.iedb.org/receptor/202723,223149,F,alphabeta,http://www.iedb.org/reference/1043033,http://www.iedb.org/epitope/2255876,IPNPKAGIM,NaN,NaN,T cell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3155,http://www.iedb.org/receptor/202724,223150,H,alphabeta,http://www.iedb.org/reference/1043033,http://www.iedb.org/epitope/2255876,IPNPKAGIM,NaN,NaN,T cell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3156,http://www.iedb.org/receptor/202725,223151,I,alphabeta,http://www.iedb.org/reference/1043033,http://www.iedb.org/epitope/2255876,IPNPKAGIM,NaN,NaN,T cell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
IEDB.columns

Index(['Receptor_Group IRI', 'Receptor_IEDB Receptor ID',
       'Receptor_Reference Name', 'Receptor_Type', 'Reference_IEDB IRI',
       'Epitope_IEDB IRI', 'Epitope_Name', 'Epitope_Source Molecule',
       'Epitope_Source Organism', 'Assay_Type', 'Assay_IEDB IDs',
       'Assay_MHC Allele Names', 'Chain 1_Type', 'Chain 1_Organism IRI',
       'Chain 1_Nucleotide Sequence', 'Chain 1_Curated V Gene',
       'Chain 1_Calculated V Gene', 'Chain 1_Curated D Gene',
       'Chain 1_Calculated D Gene', 'Chain 1_Curated J Gene',
       'Chain 1_Calculated J Gene', 'Chain 1_Protein Sequence',
       'Chain 1_Protein IRI', 'Chain 1_CDR3 Curated',
       'Chain 1_CDR3 Calculated', 'Chain 1_CDR3 Start Curated',
       'Chain 1_CDR3 End Curated', 'Chain 1_CDR3 Start Calculated',
       'Chain 1_CDR3 End Calculated', 'Chain 1_CDR1 Curated',
       'Chain 1_CDR1 Calculated', 'Chain 1_CDR1 Start Curated',
       'Chain 1_CDR1 End Curated', 'Chain 1_CDR1 Start Calculated',
       'Chain 1_CDR1 End Calculated', 'Chain 1_CDR2 Curated',
       'Chain 1_CDR2 Calculated', 'Chain 1_CDR2 Start Curated',
       'Chain 1_CDR2 End Curated', 'Chain 1_CDR2 Start Calculated',
       'Chain 1_CDR2 End Calculated', 'Chain 2_Type', 'Chain 2_Organism IRI',
       'Chain 2_Nucleotide Sequence', 'Chain 2_Curated V Gene',
       'Chain 2_Calculated V Gene', 'Chain 2_Curated D Gene',
       'Chain 2_Calculated D Gene', 'Chain 2_Curated J Gene',
       'Chain 2_Calculated J Gene', 'Chain 2_Protein Sequence',
       'Chain 2_Protein IRI', 'Chain 2_CDR3 Curated',
       'Chain 2_CDR3 Calculated', 'Chain 2_CDR3 Start Curated',
       'Chain 2_CDR3 End Curated', 'Chain 2_CDR3 Start Calculated',
       'Chain 2_CDR3 End Calculated', 'Chain 2_CDR1 Curated',
       'Chain 2_CDR1 Calculated', 'Chain 2_CDR1 Start Curated',
       'Chain 2_CDR1 End Curated', 'Chain 2_CDR1 Start Calculated',
       'Chain 2_CDR1 End Calculated', 'Chain 2_CDR2 Curated',
       'Chain 2_CDR2 Calculated', 'Chain 2_CDR2 Start Curated',
       'Chain 2_CDR2 End Curated', 'Chain 2_CDR2 Start Calculated',
       'Chain 2_CDR2 End Calculated'],
      dtype='object')

In [14]:
IEDB_clean = IEDB[['Chain 2_CDR3 Curated','Epitope_Name','Epitope_Source Molecule']]
IEDB_clean.columns = ['CDR3','Epitope','Epitope_type']
IEDB_clean

,CDR3,Epitope,Epitope_type
1,CASSYVGNTGELFF,SLLMWITQC,Cancer/testis antigen 1
2,CAISEVGVGQPQHF,AAGIGILTV,Melanoma antigen recognized by T-cells 1
3,CAISEVGVGQPQHF,AAGIGILTV,Melanoma antigen recognized by T-cells 1
4,CAISEVGVGQPQHF,ELAGIGILTV,melanoma-specific artificial polyepitopic immu...
5,ASSFIGGTDTQYF,YLEPGPVTV,NaN
...,...,...,...
3152,CSARTGYNEQFF,KLLEIAPNC,large T antigen [Merkel cell polyomavirus]
3153,YASSDKSLGGVDTGELFF,KLLEIAPNC,large T antigen [Merkel cell polyomavirus]
3154,CASEGLTYNEQFFG,IPNPKAGIM,NaN
3155,CASSEGFGTSDSGDTQYFG,IPNPKAGIM,NaN
3156,CASSFFTGISYNEQFFG,IPNPKAGIM,NaN

In [15]:
all_3_datasets = pd.concat([IEDB_clean,mc_pas_human_peptide,vdjdb_clean], axis=0)
all_3_datasets

,CDR3,Epitope,Epitope_type
1,CASSYVGNTGELFF,SLLMWITQC,Cancer/testis antigen 1
2,CAISEVGVGQPQHF,AAGIGILTV,Melanoma antigen recognized by T-cells 1
3,CAISEVGVGQPQHF,AAGIGILTV,Melanoma antigen recognized by T-cells 1
4,CAISEVGVGQPQHF,ELAGIGILTV,melanoma-specific artificial polyepitopic immu...
5,ASSFIGGTDTQYF,YLEPGPVTV,NaN
...,...,...,...
40081,CSAGTGELFF,ALDPHSGHFV,CDK4
40082,CSARVGDTGELFF,ALSPVIPHI,MLL2
40083,CASSYDSTTGELFF,ALSPVIPHI,MLL2
40084,CASTPGGYEQYF,KLFEFLVYGV,SMARCD3
40085,CASSQGYEQYF,KLFEFLVYGV,SMARCD3

In [16]:
tissue_meta_data = pd.read_csv('./Apexigen_data/PBMC_tumor_metadata_TCR_match.csv', index_col=0)
tissue_meta_data.columns

Index(['TRB_barcode', 'TRB_is_cell', 'TRB_contig_id', 'TRB_high_confidence',
       'TRB_length', 'TRB_chain', 'TRB_v_gene', 'TRB_d_gene', 'TRB_j_gene',
       'TRB_c_gene', 'TRB_full_length', 'TRB_productive', 'TRB_cdr3',
       'TRB_cdr3_nt', 'TRB_reads', 'TRB_umis', 'TRB_raw_clonotype_id',
       'TRB_raw_consensus_id', 'TRB_sample', 'TRA_is_cell', 'TRA_contig_id',
       'TRA_high_confidence', 'TRA_length', 'TRA_chain', 'TRA_v_gene',
       'TRA_d_gene', 'TRA_j_gene', 'TRA_c_gene', 'TRA_full_length',
       'TRA_productive', 'TRA_cdr3', 'TRA_cdr3_nt', 'TRA_reads', 'TRA_umis',
       'TRA_raw_clonotype_id', 'TRA_raw_consensus_id', 'TRA_sample', 'X',
       'batch', 'doublet', 'n_counts', 'n_genes', 'outcome', 'patient',
       'response', 'sample', 'timepoint', 'log_counts', 'mt_frac', 'scvi_r1',
       'cell_class', 'cell_type', 'cell_type_scvi', 'cell_class_scvi',
       'tissue'],
      dtype='object')

In [17]:
tissue_meta_data['ix'] = range(tissue_meta_data.shape[0])
tissue_meta_data['barcode'] = tissue_meta_data['TRB_barcode'] + '_' +tissue_meta_data['ix'].astype(str)

In [33]:
tissue_meta_data

,TRB_barcode,TRB_is_cell,TRB_contig_id,TRB_high_confidence,TRB_length,TRB_chain,TRB_v_gene,TRB_d_gene,TRB_j_gene,TRB_c_gene,...,log_counts,mt_frac,scvi_r1,cell_class,cell_type,cell_type_scvi,cell_class_scvi,tissue,ix,barcode
1,AAACCTGAGGCGCTCT-1,True,AAACCTGAGGCGCTCT-1_contig_2,True,499,TRB,TRBV9,NaN,TRBJ1-2,TRBC1,...,7.470794,0.032460,3,CD4T_naive,CD4T_naive3,CD4T_naive2,CD4T_naive,PBMC,0,AAACCTGAGGCGCTCT-1_0
3,AAACCTGCATGCCACG-1,True,AAACCTGCATGCCACG-1_contig_2,True,507,TRB,TRBV7-9,NaN,TRBJ2-2,TRBC2,...,7.488294,0.029659,2,CD4T_naive,CD4T_naive1,CD4T_naive1,CD4T_naive,PBMC,1,AAACCTGCATGCCACG-1_1
4,AAACCTGTCTCCTATA-1,True,AAACCTGTCTCCTATA-1_contig_2,True,799,TRB,TRBV3-1,NaN,TRBJ1-5,TRBC1,...,7.509335,0.055342,3,CD4T_naive,CD4T_naive2,CD4T_naive2,CD4T_naive,PBMC,2,AAACCTGTCTCCTATA-1_2
5,AAACGGGAGGGATACC-1,True,AAACGGGAGGGATACC-1_contig_1,True,499,TRB,TRBV7-2,NaN,TRBJ2-1,TRBC2,...,6.881412,0.075975,0,CD8T,CD8T_GrH1,CD8_GrH,CD8_T,PBMC,3,AAACGGGAGGGATACC-1_3
7,AAACGGGCATCGGAAG-1,True,AAACGGGCATCGGAAG-1_contig_2,True,517,TRB,TRBV5-5,NaN,TRBJ2-7,TRBC2,...,7.937375,0.024286,7,CD4T_naive,CD4T_naive3,CD4T_naive3,CD4T_naive,PBMC,4,AAACGGGCATCGGAAG-1_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22920,TTTCCTCCACTCGACG-1,True,TTTCCTCCACTCGACG-1_contig_1,True,681,TRB,TRBV5-1,NaN,TRBJ1-2,TRBC1,...,8.456594,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,tumor,16281,TTTCCTCCACTCGACG-1_16281
22921,TTTGCGCGTGTGCCTG-1,True,TTTGCGCGTGTGCCTG-1_contig_1,True,698,TRB,TRBV12-3,NaN,TRBJ2-5,TRBC1,...,7.969358,0.000000,3,CD8_Tcell,CD8T_GrK,CD8T_GrH,CD8_T,tumor,16282,TTTGCGCGTGTGCCTG-1_16282
22922,TTTGGTTCACCAGCAC-1,True,TTTGGTTCACCAGCAC-1_contig_1,True,521,TRB,TRBV6-5,TRBD1,TRBJ2-3,TRBC2,...,8.153062,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,tumor,16283,TTTGGTTCACCAGCAC-1_16283
22923,TTTGGTTGTTCTGGTA-1,True,TTTGGTTGTTCTGGTA-1_contig_1,True,690,TRB,TRBV7-9,NaN,TRBJ1-6,TRBC1,...,8.440744,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,tumor,16284,TTTGGTTGTTCTGGTA-1_16284
22924,TTTGTCATCTGTTGAG-1,True,TTTGTCATCTGTTGAG-1_contig_2,True,790,TRB,TRBV30,NaN,TRBJ1-2,TRBC1,...,8.111028,0.000000,4,CD8_Tcell,CD8T_GrH,CD8T_GrB,CD8_T,tumor,16285,TTTGTCATCTGTTGAG-1_16285

In [18]:
tissue_meta_data_merge_IEDB_McPAS_VDJdb = tissue_meta_data.merge(all_3_datasets, how="inner", left_on="TRB_cdr3", right_on='CDR3')

In [19]:
tissue_meta_data_merge_IEDB_McPAS_VDJdb[['TRB_cdr3']]

             TRB_cdr3
0        CASSLSVYEQYF
1    CASSLSGLAGGYEQYF
2      CASSPGLAGGEQYF
3     CASRPGGGSYNEQFF
4       CATSRVAGETQYF
..                ...
419    CASSYSGSSGELFF
420      CASSYPNQPQHF
421      CASSYPNQPQHF
422      CASSYPNQPQHF
423      CASSYPNQPQHF

[424 rows x 1 columns]

In [20]:
tissue_meta_data_merge_IEDB_McPAS_VDJdb

,TRB_barcode,TRB_is_cell,TRB_contig_id,TRB_high_confidence,TRB_length,TRB_chain,TRB_v_gene,TRB_d_gene,TRB_j_gene,TRB_c_gene,...,cell_class,cell_type,cell_type_scvi,cell_class_scvi,tissue,ix,barcode,CDR3,Epitope,Epitope_type
0,AAGGTTCAGCGATGAC-1,True,AAGGTTCAGCGATGAC-1_contig_2,True,463,TRB,TRBV28,NaN,TRBJ2-7,TRBC2,...,CD4T_naive,CD4T_naive1,CD4T_naive1,CD4T_naive,PBMC,39,AAGGTTCAGCGATGAC-1_39,CASSLSVYEQYF,LPRRSGAAGA,Influenza
1,CCGGTAGCATAGACTC-1,True,CCGGTAGCATAGACTC-1_contig_1,True,503,TRB,TRBV7-6,NaN,TRBJ2-7,TRBC2,...,CD4T_naive,CD4T_naive2,CD4T_naive2,CD4T_naive,PBMC,305,CCGGTAGCATAGACTC-1_305,CASSLSGLAGGYEQYF,EAAGIGILTV,Melanoma
2,CCTACCAAGCCTTGAT-1,True,CCTACCAAGCCTTGAT-1_contig_2,True,516,TRB,TRBV18,NaN,TRBJ2-7,TRBC2,...,CD4T_naive,CD4T_naive1,CD4T_naive1,CD4T_naive,PBMC,320,CCTACCAAGCCTTGAT-1_320,CASSPGLAGGEQYF,FLAEHEYGL,NaN
3,CGAGAAGCAAATCCGT-1,True,CGAGAAGCAAATCCGT-1_contig_1,True,502,TRB,TRBV6-5,NaN,TRBJ2-1,TRBC2,...,CD4T_naive,CD4T_naive1,CD4T_naive2,CD4T_naive,PBMC,341,CGAGAAGCAAATCCGT-1_341,CASRPGGGSYNEQFF,RLGPYLEFL,Neoantigen
4,CTAAGACGTTCCGTCT-1,True,CTAAGACGTTCCGTCT-1_contig_2,True,470,TRB,TRBV15,NaN,TRBJ2-5,TRBC2,...,CD8T,CD8T_GrH2,CD8_GrH,CD8_T,PBMC,415,CTAAGACGTTCCGTCT-1_415,CATSRVAGETQYF,FRCPRRFCF,Cytomegalovirus (CMV)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,GTCACAACAGGAATGC-1,True,GTCACAACAGGAATGC-1_contig_2,True,541,TRB,TRBV6-3,NaN,TRBJ2-2,TRBC2,...,CD8_Tcell,CD8T_GrH,CD8T_GrH,CD8_T,tumor,16209,GTCACAACAGGAATGC-1_16209,CASSYSGSSGELFF,SLLMWITQV,NY-ESO-1
420,TTGCGTCTCCACTCCA-1,True,TTGCGTCTCCACTCCA-1_contig_1,True,709,TRB,TRBV6-6,NaN,TRBJ1-5,TRBC1,...,Treg,Treg,Treg1,Treg,tumor,16277,TTGCGTCTCCACTCCA-1_16277,CASSYPNQPQHF,LLWNGPMAV,Yellow fever virus
421,TTGCGTCTCCACTCCA-1,True,TTGCGTCTCCACTCCA-1_contig_1,True,709,TRB,TRBV6-6,NaN,TRBJ1-5,TRBC1,...,Treg,Treg,Treg1,Treg,tumor,16277,TTGCGTCTCCACTCCA-1_16277,CASSYPNQPQHF,LLWNGPMAV,Yellow fever virus
422,TTGCGTCTCCACTCCA-1,True,TTGCGTCTCCACTCCA-1_contig_1,True,709,TRB,TRBV6-6,NaN,TRBJ1-5,TRBC1,...,Treg,Treg,Treg1,Treg,tumor,16277,TTGCGTCTCCACTCCA-1_16277,CASSYPNQPQHF,LLWNGPMAV,Yellow fever virus
423,TTGCGTCTCCACTCCA-1,True,TTGCGTCTCCACTCCA-1_contig_1,True,709,TRB,TRBV6-6,NaN,TRBJ1-5,TRBC1,...,Treg,Treg,Treg1,Treg,tumor,16277,TTGCGTCTCCACTCCA-1_16277,CASSYPNQPQHF,LLWNGPMAV,Yellow fever virus

In [21]:
tissue_meta_data_merge_IEDB_McPAS_VDJdb[['Epitope']].value_counts()

Epitope
GILGFVFTL                    51
LPRRSGAAGA                   44
RPHERNGFTVL                  42
VISNDVCAQV                   33
SLLMWITQV                    33
                             ..
NLNCCSVPV                     1
PQPELPYPQPE                   1
RCSDSDGLAPPQNLIRVEGNLRVEY     1
RFNLIANQHLLAPGF               1
YVLDHLIVV                     1
Name: count, Length: 63, dtype: int64

In [22]:
tissue_meta_data_merge_IEDB_McPAS_VDJdb[['Epitope_type']].value_counts()

Epitope_type
Cytomegalovirus (CMV)                                  96
Influenza                                              95
KLK3                                                   33
NY-ESO-1                                               33
Epstein Barr virus (EBV)                               23
MLANA                                                  17
PGT                                                    14
Yellow fever virus                                     12
Neoantigen                                             11
AKAP13                                                 11
ADH                                                    10
Melanoma                                                5
IGRP                                                    5
BST2                                                    4
DNAJB1-PRKACA                                           3
IGF2BP2                                                 3
ZNT8                                                    3
GCN1L1                                                  2
p53                                                     2
Human immunodeficiency virus (HIV)                      2
PTPRN                                                   2
M. tuberculosis                                         2
MAGEA6                                                  2
PLA2G6                                                  1
GAD65                                                   1
PMEL                                                    1
Celiac disease                                          1
dJ579N16.4 [Homo sapiens]                               1
SF3B1                                                   1
Epithelial ovarian cancer                               1
Cellular tumor antigen p53                              1
MUC1                                                    1
MART1                                                   1
KRAS                                                    1
G6PC2                                                   1
Insulin-like growth factor 2 mRNA-binding protein 2     1
GAD2                                                    1
IAPP                                                    1
GFAP                                                    1
transcriptional activator Tax                           1
Name: count, dtype: int64

In [23]:
all_3_datasets['Epitope'].value_counts()

Epitope
SLLMWITQV         29729
VISNDVCAQV         4070
ELAGIGILTV         3100
LPRRSGAAGA         2145
GILGFVFTL          2059
                  ...
FRNEGIHL              1
FGDVGSTLF             1
YVMAYVMAGVGS          1
SYMIMEIE              1
VHFFKNIVTPRTPG        1
Name: count, Length: 1147, dtype: int64

In [46]:
all_3_datasets[['Epitope']].drop_duplicates().to_csv("All_epitope_IEDB_McPAS_VDJdb.csv")

In [24]:
tissue_meta_data_merge_IEDB_McPAS_VDJdb = tissue_meta_data_merge_IEDB_McPAS_VDJdb.drop_duplicates()

In [43]:
tissue_meta_data_merge_IEDB_McPAS_VDJdb[['Epitope']].drop_duplicates()

         Epitope
0     LPRRSGAAGA
1     EAAGIGILTV
2      FLAEHEYGL
3      RLGPYLEFL
4      FRCPRRFCF
..           ...
360     NLIFKWIL
405    ALGDLFQSI
407  PQPELPYPQPE
409     HLKRNIVV
414    VVMSWAPPV

[63 rows x 1 columns]

In [ ]:
tissue_meta_data_merge_IEDB_McPAS_VDJdb[['Epitope']].drop_duplicates().to_csv("Apexigen_match_IEDB_McPAS_VDJdb_Epitope.csv")

In [26]:
tissue_meta_data_merge_IEDB_McPAS_VDJdb.to_csv("Apexigen_match_IEDB_McPAS_VDJdb_all_data.csv")

In [27]:
tissue_meta_data_merge_IEDB_McPAS_VDJdb

,TRB_barcode,TRB_is_cell,TRB_contig_id,TRB_high_confidence,TRB_length,TRB_chain,TRB_v_gene,TRB_d_gene,TRB_j_gene,TRB_c_gene,...,cell_class,cell_type,cell_type_scvi,cell_class_scvi,tissue,ix,barcode,CDR3,Epitope,Epitope_type
0,AAGGTTCAGCGATGAC-1,True,AAGGTTCAGCGATGAC-1_contig_2,True,463,TRB,TRBV28,NaN,TRBJ2-7,TRBC2,...,CD4T_naive,CD4T_naive1,CD4T_naive1,CD4T_naive,PBMC,39,AAGGTTCAGCGATGAC-1_39,CASSLSVYEQYF,LPRRSGAAGA,Influenza
1,CCGGTAGCATAGACTC-1,True,CCGGTAGCATAGACTC-1_contig_1,True,503,TRB,TRBV7-6,NaN,TRBJ2-7,TRBC2,...,CD4T_naive,CD4T_naive2,CD4T_naive2,CD4T_naive,PBMC,305,CCGGTAGCATAGACTC-1_305,CASSLSGLAGGYEQYF,EAAGIGILTV,Melanoma
2,CCTACCAAGCCTTGAT-1,True,CCTACCAAGCCTTGAT-1_contig_2,True,516,TRB,TRBV18,NaN,TRBJ2-7,TRBC2,...,CD4T_naive,CD4T_naive1,CD4T_naive1,CD4T_naive,PBMC,320,CCTACCAAGCCTTGAT-1_320,CASSPGLAGGEQYF,FLAEHEYGL,NaN
3,CGAGAAGCAAATCCGT-1,True,CGAGAAGCAAATCCGT-1_contig_1,True,502,TRB,TRBV6-5,NaN,TRBJ2-1,TRBC2,...,CD4T_naive,CD4T_naive1,CD4T_naive2,CD4T_naive,PBMC,341,CGAGAAGCAAATCCGT-1_341,CASRPGGGSYNEQFF,RLGPYLEFL,Neoantigen
4,CTAAGACGTTCCGTCT-1,True,CTAAGACGTTCCGTCT-1_contig_2,True,470,TRB,TRBV15,NaN,TRBJ2-5,TRBC2,...,CD8T,CD8T_GrH2,CD8_GrH,CD8_T,PBMC,415,CTAAGACGTTCCGTCT-1_415,CATSRVAGETQYF,FRCPRRFCF,Cytomegalovirus (CMV)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,TTTACTGCACTTGGAT-1,True,TTTACTGCACTTGGAT-1_contig_1,True,693,TRB,TRBV7-9,TRBD2,TRBJ2-5,TRBC2,...,Treg,Treg,Treg1,Treg,tumor,15981,TTTACTGCACTTGGAT-1_15981,CASSLSGGGETQYF,NLSALGIFST,Insulin-like growth factor 2 mRNA-binding prot...
417,TTTGCGCTCCTTTACA-1,True,TTTGCGCTCCTTTACA-1_contig_3,True,537,TRB,TRBV6-3,NaN,TRBJ2-2,TRBC2,...,CD8_Tcell,CD8T_GrH,CD8T_GrH,CD8_T,tumor,15992,TTTGCGCTCCTTTACA-1_15992,CASSYSGSSGELFF,SLLMWITQV,NY-ESO-1
418,AGCAGCCAGGTGCTTT-1,True,AGCAGCCAGGTGCTTT-1_contig_1,True,688,TRB,TRBV25-1,TRBD2,TRBJ2-7,TRBC2,...,T/NK,Teff/NK,CD8T_GrB,CD8_T,tumor,16040,AGCAGCCAGGTGCTTT-1_16040,CASSVAGGAYEQYF,LLWNGPMAV,Yellow fever virus
419,GTCACAACAGGAATGC-1,True,GTCACAACAGGAATGC-1_contig_2,True,541,TRB,TRBV6-3,NaN,TRBJ2-2,TRBC2,...,CD8_Tcell,CD8T_GrH,CD8T_GrH,CD8_T,tumor,16209,GTCACAACAGGAATGC-1_16209,CASSYSGSSGELFF,SLLMWITQV,NY-ESO-1
420,TTGCGTCTCCACTCCA-1,True,TTGCGTCTCCACTCCA-1_contig_1,True,709,TRB,TRBV6-6,NaN,TRBJ1-5,TRBC1,...,Treg,Treg,Treg1,Treg,tumor,16277,TTGCGTCTCCACTCCA-1_16277,CASSYPNQPQHF,LLWNGPMAV,Yellow fever virus

In [28]:
tissue_meta_data_merge_IEDB_McPAS_VDJdb.drop_duplicates()

,TRB_barcode,TRB_is_cell,TRB_contig_id,TRB_high_confidence,TRB_length,TRB_chain,TRB_v_gene,TRB_d_gene,TRB_j_gene,TRB_c_gene,...,cell_class,cell_type,cell_type_scvi,cell_class_scvi,tissue,ix,barcode,CDR3,Epitope,Epitope_type
0,AAGGTTCAGCGATGAC-1,True,AAGGTTCAGCGATGAC-1_contig_2,True,463,TRB,TRBV28,NaN,TRBJ2-7,TRBC2,...,CD4T_naive,CD4T_naive1,CD4T_naive1,CD4T_naive,PBMC,39,AAGGTTCAGCGATGAC-1_39,CASSLSVYEQYF,LPRRSGAAGA,Influenza
1,CCGGTAGCATAGACTC-1,True,CCGGTAGCATAGACTC-1_contig_1,True,503,TRB,TRBV7-6,NaN,TRBJ2-7,TRBC2,...,CD4T_naive,CD4T_naive2,CD4T_naive2,CD4T_naive,PBMC,305,CCGGTAGCATAGACTC-1_305,CASSLSGLAGGYEQYF,EAAGIGILTV,Melanoma
2,CCTACCAAGCCTTGAT-1,True,CCTACCAAGCCTTGAT-1_contig_2,True,516,TRB,TRBV18,NaN,TRBJ2-7,TRBC2,...,CD4T_naive,CD4T_naive1,CD4T_naive1,CD4T_naive,PBMC,320,CCTACCAAGCCTTGAT-1_320,CASSPGLAGGEQYF,FLAEHEYGL,NaN
3,CGAGAAGCAAATCCGT-1,True,CGAGAAGCAAATCCGT-1_contig_1,True,502,TRB,TRBV6-5,NaN,TRBJ2-1,TRBC2,...,CD4T_naive,CD4T_naive1,CD4T_naive2,CD4T_naive,PBMC,341,CGAGAAGCAAATCCGT-1_341,CASRPGGGSYNEQFF,RLGPYLEFL,Neoantigen
4,CTAAGACGTTCCGTCT-1,True,CTAAGACGTTCCGTCT-1_contig_2,True,470,TRB,TRBV15,NaN,TRBJ2-5,TRBC2,...,CD8T,CD8T_GrH2,CD8_GrH,CD8_T,PBMC,415,CTAAGACGTTCCGTCT-1_415,CATSRVAGETQYF,FRCPRRFCF,Cytomegalovirus (CMV)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,TTTACTGCACTTGGAT-1,True,TTTACTGCACTTGGAT-1_contig_1,True,693,TRB,TRBV7-9,TRBD2,TRBJ2-5,TRBC2,...,Treg,Treg,Treg1,Treg,tumor,15981,TTTACTGCACTTGGAT-1_15981,CASSLSGGGETQYF,NLSALGIFST,Insulin-like growth factor 2 mRNA-binding prot...
417,TTTGCGCTCCTTTACA-1,True,TTTGCGCTCCTTTACA-1_contig_3,True,537,TRB,TRBV6-3,NaN,TRBJ2-2,TRBC2,...,CD8_Tcell,CD8T_GrH,CD8T_GrH,CD8_T,tumor,15992,TTTGCGCTCCTTTACA-1_15992,CASSYSGSSGELFF,SLLMWITQV,NY-ESO-1
418,AGCAGCCAGGTGCTTT-1,True,AGCAGCCAGGTGCTTT-1_contig_1,True,688,TRB,TRBV25-1,TRBD2,TRBJ2-7,TRBC2,...,T/NK,Teff/NK,CD8T_GrB,CD8_T,tumor,16040,AGCAGCCAGGTGCTTT-1_16040,CASSVAGGAYEQYF,LLWNGPMAV,Yellow fever virus
419,GTCACAACAGGAATGC-1,True,GTCACAACAGGAATGC-1_contig_2,True,541,TRB,TRBV6-3,NaN,TRBJ2-2,TRBC2,...,CD8_Tcell,CD8T_GrH,CD8T_GrH,CD8_T,tumor,16209,GTCACAACAGGAATGC-1_16209,CASSYSGSSGELFF,SLLMWITQV,NY-ESO-1
420,TTGCGTCTCCACTCCA-1,True,TTGCGTCTCCACTCCA-1_contig_1,True,709,TRB,TRBV6-6,NaN,TRBJ1-5,TRBC1,...,Treg,Treg,Treg1,Treg,tumor,16277,TTGCGTCTCCACTCCA-1_16277,CASSYPNQPQHF,LLWNGPMAV,Yellow fever virus

In [ ]:
all_3_datasets.drop_duplicates().to_csv("Merged_IEDB_McPAS_VDJdb_TCR_peptide_peptide_type.csv")

In [35]:
all_3_datasets['ix'] = range(all_3_datasets.shape[0])

In [37]:
all_3_datasets = all_3_datasets.drop_duplicates()

In [ ]:
all_3_datasets.to_csv("Merged_IEDB_McPAS_VDJdb_TCR_peptide_peptide_type.csv")

In [42]:
all_3_datasets[['CDR3','Epitope']].drop_duplicates().to_csv("Merged_IEDB_McPAS_VDJdb_TCR_peptide_peptide_type_TCR_peptide_pair_unique.csv")

In [41]:
all_3_datasets

,CDR3,Epitope,Epitope_type,ix
1,CASSYVGNTGELFF,SLLMWITQC,Cancer/testis antigen 1,0
2,CAISEVGVGQPQHF,AAGIGILTV,Melanoma antigen recognized by T-cells 1,1
3,CAISEVGVGQPQHF,AAGIGILTV,Melanoma antigen recognized by T-cells 1,2
4,CAISEVGVGQPQHF,ELAGIGILTV,melanoma-specific artificial polyepitopic immu...,3
5,ASSFIGGTDTQYF,YLEPGPVTV,NaN,4
...,...,...,...,...
40081,CSAGTGELFF,ALDPHSGHFV,CDK4,56808
40082,CSARVGDTGELFF,ALSPVIPHI,MLL2,56809
40083,CASSYDSTTGELFF,ALSPVIPHI,MLL2,56810
40084,CASTPGGYEQYF,KLFEFLVYGV,SMARCD3,56811
40085,CASSQGYEQYF,KLFEFLVYGV,SMARCD3,56812

In [48]:
all_3_datasets['CDR3'].nunique()

46779